### ISSUE TITLE
Unable to fetch products locally

### ISSUE THREAD

**Issue by findtoni** [mercurieinc/obudu#13]
**Network error: Response not successful: Received status code 400**

I'm getting that error when running Obudu on local. Products don't populate.

**Comment by enkaypeter** [comment]
I'll add an expiry date to cart items so it can clear itself. You can clear your localStorage to re-fetch products again.

**Comment by findtoni** [comment]
I've cleared my local storage on Chrome dev, still not able to fetch the products.

**Comment by findtoni** [comment]
**Fix** `rm -rf node_modules && npm install`
