### ISSUE TITLE
Single products page

### ISSUE THREAD

**Issue by enkaypeter** [mercurieinc/obudu#8]
The dropdown on the singles product page isn't selecting. Please take a look @findtoni 

![Screen-Recording-2019-08-21-at-19 40 49](https://user-images.githubusercontent.com/26356148/63459890-5212cb00-c44d-11e9-9d50-9647781e39b2.gif)

**Comment by enkaypeter** [comment]
> The dropdown on the singles product page isn't selecting. Please take a look @findtoni
> 
> ![Screen-Recording-2019-08-21-at-19 40 49](https://user-images.githubusercontent.com/26356148/63459890-5212cb00-c44d-11e9-9d50-9647781e39b2.gif)

commit id: `93eb4ef`

**Comment by findtoni** [comment]
Fixed
